---
- name: 'Clear sources'
  copy:
    content: ""
    dest: /etc/apt/sources.list
    force: yes
    group: root
    owner: root
    mode: 0644

- name: Add source repository into sources list
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes

  with_items:
  - "deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse"
  - "deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse"
  - "deb http://archive.ubuntu.com/ubuntu focal-security main restricted universe multiverse"
  - "deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse"
  when: ansible_architecture == "x86_64"

- name: Install locale
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: 
  with_items:
  - locales 

- name: Set timezone to UTC
  community.general.timezone:
    name: UTC

- name: Configure locale to '{{ config_system_locale }}' and language to '{{ config_system_language }}'
  command: localectl set-locale LANG={{ config_system_locale }} LANGUAGE={{ config_system_language }}

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: remove packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  environment:
    DEBIAN_FRONTEND: noninteractive
  loop: "{{ packages_to_remove }}"

- name: Full upgrade of packages
  ansible.builtin.apt:
    upgrade: full
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Delete content & directory
  file:
    state: absent
    path: /home/mydata/web/
  loop: "{{ folders_to_remove }}"

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive
  loop: "{{ packages_to_install }}"